version: '3'
services:
  db:
    image: 'postgres:14-alpine'
    ports:
      - '5432:5432'
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    env_file:
      - 'secrets.env'
