[build]
  publish = 'build/dist/'

[functions]
  directory = 'build/functions/'

[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
