[build]
  publish = 'build/dist/'

[functions]
  directory = 'build/functions/'

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
